FROM redis:alpine

# Copy a custom redis.conf file (with custom port settings) into the container
# COPY redis.conf ./redis/redis.conf

# Expose the custom port (e.g., 6380)
# EXPOSE 6380

# Run Redis with the custom configuration
# CMD ["redis-server", "./redis/redis.conf"]
